export type ThemeInfo = {
  id: string;
  name: string;
  isDark: boolean;
  previewColors: string[];
};

export const THEMES: ThemeInfo[] = [
  { id: 'default', name: 'Default', isDark: true, previewColors: ['#2e3a4e', '#f9a826', '#3b4a60'] },
  { id: 'void', name: 'Void', isDark: true, previewColors: ['#0f0f13', '#7d26e9', '#440b80'] },
  { id: 'bright', name: 'Bright', isDark: false, previewColors: ['#f4fce3', '#39bdf8', '#dcfce7'] },
  { id: 'crimson', name: 'Crimson', isDark: true, previewColors: ['#5c0d16', '#ffffff', '#1a1a1a'] },
  { id: 'jade', name: 'Jade', isDark: false, previewColors: ['#eff6f3', '#16a34a', '#d1fae5'] },
  { id: 'amber-dark', name: 'Amber Dark', isDark: true, previewColors: ["#1a1f26", "#ffbf00", "#2c343f"] },
  { id: 'apricot-light', name: 'Apricot Light', isDark: false, previewColors: ["#fff7ed", "#ffa33b", "#ffeacc"] },
  { id: 'aqua-dark', name: 'Aqua Dark', isDark: true, previewColors: ["#142121", "#14c7c7", "#243a3a"] },
  { id: 'azure-dark', name: 'Azure Dark', isDark: true, previewColors: ["#1a232e", "#3b9eff", "#2d3a4c"] },
  { id: 'baby-blue-light', name: 'Baby Blue Light', isDark: false, previewColors: ["#eff8fe", "#0091ff", "#d5eeff"] },
  { id: 'blue-gray-dark', name: 'Blue Gray Dark', isDark: true, previewColors: ["#1e252e", "#6398de", "#313c4a"] },
  { id: 'bronze-dark', name: 'Bronze Dark', isDark: true, previewColors: ["#241e1a", "#d98644", "#3d322c"] },
  { id: 'burgundy-dark', name: 'Burgundy Dark', isDark: true, previewColors: ["#291a1e", "#f22b59", "#452d34"] },
  { id: 'canary-light', name: 'Canary Light', isDark: false, previewColors: ["#feffed", "#e5c500", "#fcfdda"] },
  { id: 'celadon-light', name: 'Celadon Light', isDark: false, previewColors: ["#f2f9f2", "#66b366", "#dcefdc"] },
  { id: 'cerulean-light', name: 'Cerulean Light', isDark: false, previewColors: ["#eff6fe", "#0091ff", "#d5e9fd"] },
  { id: 'charcoal-dark', name: 'Charcoal Dark', isDark: true, previewColors: ["#1a1d21", "#598bc4", "#2c3138"] },
  { id: 'chartreuse-light', name: 'Chartreuse Light', isDark: false, previewColors: ["#f7ffed", "#99e500", "#eafdda"] },
  { id: 'cobalt-dark', name: 'Cobalt Dark', isDark: true, previewColors: ["#17222e", "#2b73f3", "#2a394c"] },
  { id: 'coffee-light', name: 'Coffee Light', isDark: false, previewColors: ["#f7f2ed", "#99663b", "#e9decf"] },
  { id: 'copper-dark', name: 'Copper Dark', isDark: true, previewColors: ["#291e1c", "#c4672c", "#45332f"] },
  { id: 'coral-light', name: 'Coral Light', isDark: false, previewColors: ["#fff5ed", "#ff6b47", "#ffe5d9"] },
  { id: 'cornflower-light', name: 'Cornflower Light', isDark: false, previewColors: ["#f0f5fe", "#6b9bff", "#d9e5fd"] },
  { id: 'cream-light', name: 'Cream Light', isDark: false, previewColors: ["#fcf8f0", "#d9a444", "#f5eada"] },
  { id: 'crimson-dark', name: 'Crimson Dark', isDark: true, previewColors: ["#211417", "#f22b59", "#3a2429"] },
  { id: 'cyan-dark', name: 'Cyan Dark', isDark: true, previewColors: ["#1a2424", "#14c7c7", "#2d4040"] },
  { id: 'denim-dark', name: 'Denim Dark', isDark: true, previewColors: ["#1d2229", "#598ac4", "#303945"] },
  { id: 'emerald-dark', name: 'Emerald Dark', isDark: true, previewColors: ["#14211a", "#14c767", "#243a2c"] },
  { id: 'forest-dark', name: 'Forest Dark', isDark: true, previewColors: ["#172417", "#2ff22f", "#294029"] },
  { id: 'fuchsia-dark', name: 'Fuchsia Dark', isDark: true, previewColors: ["#241a22", "#f22bd5", "#3f2c3b"] },
  { id: 'gold-dark', name: 'Gold Dark', isDark: true, previewColors: ["#211f14", "#ffbf00", "#3a3624"] },
  { id: 'grape-light', name: 'Grape Light', isDark: false, previewColors: ["#f7f0fe", "#a347ff", "#ebd9fd"] },
  { id: 'honeydew-light', name: 'Honeydew Light', isDark: false, previewColors: ["#f2fcf5", "#8bc495", "#deefdf"] },
  { id: 'indigo-dark', name: 'Indigo Dark', isDark: true, previewColors: ["#1d1a29", "#7347ff", "#302c45"] },
  { id: 'iris-dark', name: 'Iris Dark', isDark: true, previewColors: ["#201e2b", "#8663de", "#363248"] },
  { id: 'jade-dark', name: 'Jade Dark', isDark: true, previewColors: ["#182420", "#2bd596", "#2b4038"] },
  { id: 'khaki-light', name: 'Khaki Light', isDark: false, previewColors: ["#f7f5ed", "#a6883b", "#e9e3cf"] },
  { id: 'lavender-light', name: 'Lavender Light', isDark: false, previewColors: ["#f5f0fe", "#8c6bf3", "#e5d9fd"] },
  { id: 'lemon-light', name: 'Lemon Light', isDark: false, previewColors: ["#feffed", "#e5c500", "#fcfdda"] },
  { id: 'lilac-light', name: 'Lilac Light', isDark: false, previewColors: ["#f9f2fb", "#c47add", "#eedff2"] },
  { id: 'lime-light', name: 'Lime Light', isDark: false, previewColors: ["#f5ffed", "#7fe500", "#e7fdda"] },
  { id: 'magenta-dark', name: 'Magenta Dark', isDark: true, previewColors: ["#261a24", "#f22bcd", "#422c3e"] },
  { id: 'maroon-dark', name: 'Maroon Dark', isDark: true, previewColors: ["#211414", "#c72424", "#3a2424"] },
  { id: 'mauve-light', name: 'Mauve Light', isDark: false, previewColors: ["#f7f2f7", "#996699", "#e9dee9"] },
  { id: 'midnight-dark', name: 'Midnight Dark', isDark: true, previewColors: ["#141724", "#5973c4", "#24293f"] },
  { id: 'mint-light', name: 'Mint Light', isDark: false, previewColors: ["#f0fbf7", "#24c783", "#d9f2e9"] },
  { id: 'navy-dark', name: 'Navy Dark', isDark: true, previewColors: ["#151e2b", "#2b6bf3", "#273448"] },
  { id: 'olive-dark', name: 'Olive Dark', isDark: true, previewColors: ["#1e2114", "#a2c724", "#333a24"] },
  { id: 'onyx-dark', name: 'Onyx Dark', isDark: true, previewColors: ["#0d0e12", "#3b598d", "#22252e"] },
  { id: 'orchid-dark', name: 'Orchid Dark', isDark: true, previewColors: ["#221a24", "#c447e0", "#3b2c3e"] },
  { id: 'peach-light', name: 'Peach Light', isDark: false, previewColors: ["#fff5f0", "#ff8c6b", "#ffe5da"] },
  { id: 'periwinkle-light', name: 'Periwinkle Light', isDark: false, previewColors: ["#f2f5fd", "#7f8cff", "#dfe3f5"] },
  { id: 'pistachio-light', name: 'Pistachio Light', isDark: false, previewColors: ["#f7fcf2", "#95c470", "#e9efde"] },
  { id: 'plum-dark', name: 'Plum Dark', isDark: true, previewColors: ["#211421", "#e033e0", "#3a243a"] },
  { id: 'rose-light', name: 'Rose Light', isDark: false, previewColors: ["#fdf2f5", "#ff6b95", "#f5dbe3"] },
  { id: 'ruby-dark', name: 'Ruby Dark', isDark: true, previewColors: ["#29181d", "#f22b4e", "#452a31"] },
  { id: 'sapphire-dark', name: 'Sapphire Dark', isDark: true, previewColors: ["#171e29", "#2b6bf3", "#293345"] },
  { id: 'scarlet-light', name: 'Scarlet Light', isDark: false, previewColors: ["#fff2ed", "#ff5e3b", "#ffdecf"] },
  { id: 'seafoam-light', name: 'Seafoam Light', isDark: false, previewColors: ["#f0faf8", "#3bd9ac", "#d9f0ea"] },
  { id: 'sky-light', name: 'Sky Light', isDark: false, previewColors: ["#eff7fe", "#0091ff", "#d5ecfd"] },
  { id: 'slate-dark', name: 'Slate Dark', isDark: true, previewColors: ["#181c22", "#5c85ad", "#2a303b"] },
  { id: 'tangerine-light', name: 'Tangerine Light', isDark: false, previewColors: ["#fff7ed", "#ffa33b", "#ffeacc"] },
  { id: 'teal-dark', name: 'Teal Dark', isDark: true, previewColors: ["#14211e", "#24c799", "#243a34"] },
  { id: 'topaz-dark', name: 'Topaz Dark', isDark: true, previewColors: ["#172229", "#2bb6f3", "#2a3945"] },
  { id: 'violet-dark', name: 'Violet Dark', isDark: true, previewColors: ["#1d1a29", "#a347ff", "#302c45"] },
  { id: 'wisteria-light', name: 'Wisteria Light', isDark: false, previewColors: ["#f5f2fd", "#9f7fff", "#e5dff5"] }
];
